### ISSUE TITLE
Problems with nbextensions

### ISSUE THREAD

**Issue by taylorsansom** [gforsyth/numba_tutorial_scipy2017#4]
I wasn't able to get the localhost:8888/nbextensions to work with the command

``pip install https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip --user`` 

Not sure what the issue is but kept getting 404 not found. Had to install nbextensions ([from here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions)) with

``conda install -c conda-forge jupyter_contrib_nbextensions``

to get it to work.

**Comment by gforsyth** [comment]
Whoops. Nice spot. I meant to change the instructions to point at conda
forge. Thanks for letting me know!

**Comment by gforsyth** [comment]
Closed via a7f8926cc1d14264d
