### ISSUE TITLE
Cavity Flow Exercises

### ISSUE THREAD

**Issue by jrleeman** [gforsyth/numba_tutorial_scipy2017#5]
A couple of issues in the `05.Cavity.Flow.Exercises.ipynb` notebook

* [x] Missing colon at the end of this line in second code cell `while iter_diff > l2_target and n <= 500:`
* [x] Loading IC and answer pickles needs to be `../fname` to go up a directory.

**Comment by gforsyth** [comment]
Thanks, @jrleeman !

**Comment by jrleeman** [comment]
No problem! Thanks for the great tutorial and all of the work you've put into it!
